### ISSUE TITLE
cannot parse dictionary at <address>

### ISSUE THREAD

**Issue by rpelorosso** [mrmacete/r2-ggpack#1]
Hi! I'm trying to export the .wimpy files from ThimbleweedPark.ggpack1. Some work fine, but there are others that trigger an error, such as 

```
[0x00000000]> s sym.Vista.wimpy
[0x04fbc35f]> =!pDj
cannot parse dictionary at 0x4fbc35f
```

or 

```
[0x0473907a]> s sym.MainStreet.wimpy
[0x03e6d4d8]> =!pDj
cannot parse dictionary at 0x3e6d4d8
```
 
Among others. Is there any way to export these?

Thank you! 
Rodrigo

**Comment by mrmacete** [comment]
hey! nice catch! probably you found a bug. 

i'll try to reproduce and fix it ASAP.

meanwhile, if you're in the mood for investigating more, you can:

- enable debug output by turning that `0` into a `1` here: https://github.com/mrmacete/r2-ggpack/blob/master/gglib.c#L9 (and optionally here: https://github.com/mrmacete/r2-ggpack/blob/master/io_ggpack.c#L14 but be prepared for a lot of noise)
- recompile and install from source
- see what output you get while executing the failing command
- paste it here
- if you want to go and fix the bug yourself you're welcome to do a PR ;)

cheers

**Comment by rpelorosso** [comment]
Thank you! I'll try those steps, and will report on whatever I can find.

**Comment by rpelorosso** [comment]
@mrmacete  Well, I was expecting a lot more noise. (unless, of course, I did something wrong). I compiled from source having enabled debugging in both files. This is the output:

```
[silencer@myhostname ThimblePack]$ r2 -w ggpack://ThimbleweedPark.ggpack1
gg_value_carve: unsupported type 14
gg_hash_carve: could not carve value
retry with version 1
 -- Find wide-char strings with the '/w <string>' command
[0x00000000]> s sym.Vista.wimpy
[0x04fbc35f]> =!pDj
gg_value_carve: unsupported type 6
gg_hash_carve: could not carve value
gg_value_carve: error on array item 0
gg_hash_carve: could not carve value
cannot parse dictionary at 0x4fbc35f
[0x04fbc35f]> 
```

Thank you!!

**Comment by mrmacete** [comment]
thanks!

this commit should solve the problem: https://github.com/mrmacete/r2-ggpack/commit/dfabda10642ff3dbc1139c049478e301578fd5cf

feel free to reopen if that's not the case.

cheers

**Comment by rpelorosso** [comment]
Thank you @mrmacete !! The commit indeed fixes the issue :D 

I have to ask, how did you know that type 6 was Double? I had a look at the code, trying to figure out how to solve the issue, but could not figure out what type should 6 be.

**Comment by rpelorosso** [comment]
@mrmacete  I'm sorry I had to open this again :(  Although the commit fixes the issues with sym.Vista.wimpy, I've found that there are still a couple of files than can't be extracted, such as:

```
[0x00000000]> s sym.ReyesAnimation.json
[0x0464a016]> =!pDj
gg_value_carve: unsupported type 1
gg_value_carve: error on array item 0
gg_hash_carve: could not carve value
gg_value_carve: error on array item 0
gg_hash_carve: could not carve value
gg_value_carve: error on array item 60
gg_hash_carve: could not carve value
cannot parse dictionary at 0x464a016
[0x0464a016]> 
```

Please let me know if you need any more information, and of course, grazie mille! :)
